version: '3.8'
services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

    command: sleep infinity
    network_mode: host
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
    
volumes:
  pgdata: 