databases:
  - name: autonomia-postgres
    databaseName: telegram
    plan: free

services:
  - type: web
    name: autonomia
    region: frankfurt
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autonomia-postgres
          property: connectionString
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELETHON_SESSION
        value: autonomia
      - key: TELETHON_SESSION_STRING
        sync: false
      - key: PHONE_NUMBER
        sync: false
      - key: NEBIUS_STUDIO_API_KEY
        sync: false
        
    healthCheckPath: /api/v1/health
