databases:
  - name: autonomia-postgres
    region: frankfurt
    databaseName: telegram
    plan: basic-256mb

services:
  - type: web
    name: autonomia
    region: frankfurt
    runtime: docker
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autonomia-postgres
          property: connectionString

      # Admin Panel Configuration
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false

      # Telegram Configuration
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELETHON_SESSION
        value: autonomia
      - key: TELETHON_SESSION_STRING
        sync: false
      - key: PHONE_NUMBER
        sync: false
      - key: NEBIUS_STUDIO_API_KEY
        sync: false

    healthCheckPath: /api/v1/health
