"""initial migration

Revision ID: 56c0a821a9be
Revises:
Create Date: 2025-07-20 11:05:05.650870

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56c0a821a9be"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_configs",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("save_messages", sa.Boolean(), nullable=False),
        sa.Column("load_from_date", sa.DateTime(), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=True),
        sa.Column("answer_threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "events",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("utc_dttm", sa.DateTime(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("event_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("chat_configs")
    # ### end Alembic commands ###
