"""update_message_model

Revision ID: 77f45b6826fc
Revises: 561461e64c14
Create Date: 2025-07-24 16:02:07.232633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f45b6826fc'
down_revision: Union[str, Sequence[str], None] = '561461e64c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_users_bot_verified'), table_name='users')
    op.drop_index(op.f('ix_users_premium'), table_name='users')
    \
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_premium'), 'users', ['is_premium'], unique=False)
    op.create_index(op.f('ix_users_bot_verified'), 'users', ['is_bot', 'is_verified'], unique=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
