"""add_enriched_message_table

Revision ID: 9b4e71c8bc90
Revises: 77f45b6826fc
Create Date: 2025-07-24 20:29:08.359973

"""

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b4e71c8bc90"
down_revision: Union[str, Sequence[str], None] = "77f45b6826fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "messages_enriched",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("meaning", sa.String(), nullable=True),
        sa.Column("embeddings", Vector(4096), nullable=True),
        sa.PrimaryKeyConstraint("chat_id", "message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages_enriched")
    # ### end Alembic commands ###
